"""Create habit table

Revision ID: 1b4ab2f0ef88
Revises: 6b3988e38798
Create Date: 2026-02-07 20:14:47.854901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b4ab2f0ef88'
down_revision: Union[str, Sequence[str], None] = '6b3988e38798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('frequency_type', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='frequencytype'), nullable=False),
    sa.Column('times_per_period', sa.Integer(), nullable=False),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('preferred_times', postgresql.ARRAY(sa.Time()), nullable=True),
    sa.Column('target_streak', sa.Integer(), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_completions', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Integer(), nullable=False),
    sa.Column('allow_partial', sa.Boolean(), nullable=False),
    sa.Column('require_notes', sa.Boolean(), nullable=False),
    sa.Column('require_mood', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('custom_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_index(op.f('ix_habits_title'), 'habits', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habits_title'), table_name='habits')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
