"""Add used at column in access restore table

Revision ID: 7eb4dd81ef5e
Revises: ade44684269c
Create Date: 2026-01-31 13:08:20.849191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb4dd81ef5e'
down_revision: Union[str, Sequence[str], None] = 'ade44684269c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_restores', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_restores', 'used_at')
    # ### end Alembic commands ###
